const encouragements = [
    "Waaaw tu avances bien !",
    "Bravo, continue comme ça !",
    "Excellent travail, continue !",
    "Super, tu es sur la bonne voie !",
    "Génial, ne t'arrête pas maintenant !",
    "Formidable, tu progresses vite !",
    "Impressionnant, continue comme ça !",
    "Fantastique, tu fais du bon travail !",
    "Splendide, tu es en train de réussir !",
    "Extraordinaire, continue ton bon travail !",
    "Bravo, tu fais des merveilles !",
    "Superbe, tu es incroyable !",
    "Incroyable, ne lâche rien !",
    "Magnifique, tu y es presque !",
    "Excellent, tu es doué !",
    "Fantastique, tu fais des progrès !",
    "Bien joué, tu t'améliores !",
    "Génial, continue sur cette lancée !",
    "Parfait, tu fais des merveilles !",
    "Top, tu es sur la bonne route !",
    "Sublime, tu es en progrès constant !",
    "Super, ne t'arrête pas !",
    "Bravo, tu es vraiment bon !",
    "Formidable, tu réussis bien !",
    "Bien, tu avances très bien !"
];
